# -*- coding: utf-8 -*-
"""CONVOLUCION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RoWFhFPy0Zr-TRiHKp9w1siPisPQwQEK
"""

import matplotlib.pyplot as plt
import matplotlib.image as img
import numpy as np
from google.colab import files
from io import BytesIO
from PIL import Image

"""SUBIENDO IMAGEN A GOOGLE COLAB

"""

uploaded = files.upload()

"""VISUALIZAR IMAGEN"""

lena = Image.open(BytesIO(uploaded['lena.png']))
plt.imshow(lena)
plt.show()

"""PASANDO IMAGEN A MATRIZ"""

lena= img.imread('lena.png')
print (lena.shape)
m,n = lena.shape

"""MODIFICANDO IMAGEN"""

plt.inshow(lena, cmap= 'gray')
plt.show

new_image= np.zeros(m,n)

for i in range (m):
  for j in range (n):
    print(lena[i,j])
    if lena(i,j)>0.8:
      new_image[i,j]=1
    else:
      new_image[i,j]=lena[i,j]

plt.subplot[1,2,1]
plt.inshow(lena, cmap= 'gray')
plt.subplot[1,2,2]
plt.inshow(lena, cmap= 'gray')
plt.show

kernel= np.zeros([3,3], dtype=int)
kernel[1][1]=0
print(kernel)

for i in range (1, m-1):
  for j in range(1, n-1):
    sum= lena[i-1,j-1]*kernel[0][0]+lena[i-1,j]+lena[i-1,j+1]+lena[i,j-1]+lena[i,j]+lena[i,j+1]